"""Model changes

Revision ID: 065f99998d45
Revises: 0e1a82664ea0
Create Date: 2025-10-10 11:06:59.129224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '065f99998d45'
down_revision: Union[str, None] = '0e1a82664ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_id', sa.Integer(), nullable=False, default=1))
    op.add_column('users', sa.Column('plan_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'plan_expiry')
    op.drop_column('users', 'plan_id')
    # ### end Alembic commands ###
